backend:
  name: git-gateway
  branch: main # or master

media_folder: "images" # Where images will be uploaded
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts" # Where your posts will be saved
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
