backend:
  name: git-gateway
  repo: kby122319/bukidcamp-cms
  branch: main # or master

media_folder: "images" # Where images will be uploaded
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Static Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
